FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine

LABEL maintainer="yasin.akar@vtc.com.tr"

USER root

RUN apk add --no-cache \
        bash \
        bash-doc \
        bash-completion \
        wget \
        coreutils \
        autoconf \
        build-base \
        linux-headers \
        gcc \
        gfortran \
        g++ \
        make \
        cmake \
        R \
        R-dev
