name: Build ASP.NET Core 8.0 Runtime with Python Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  DOTNET_VERSION: 8.0
  PYTHON_VERSION: 3.11
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}

jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build '${{ github.repository_owner }}/aspnet-n-python:${{ env.DOTNET_VERSION }}'
        run: |
          docker build \
              --file images/aspnet-n-python/Dockerfile \
              --build-arg DOTNET_VERSION=${{ env.DOTNET_VERSION }} \
              --build-arg PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
              --tag ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/aspnet-n-python:${{ env.DOTNET_VERSION }} \
              images/aspnet-n-python/

      - name: Login to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push '${{ github.repository_owner }}/aspnet-n-python:${{ env.DOTNET_VERSION }}'
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/aspnet-n-python:${{ env.DOTNET_VERSION }}