name: Build RabbitMQ Docker Image(s)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}

jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build '${{ github.repository_owner }}/rabbitmq:latest'
        run: |
          docker build \
              --file images/rabbitmq/latest/Dockerfile \
              --tag ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/rabbitmq:latest \
              images/rabbitmq/latest/

      - name: Build '${{ github.repository_owner }}/rabbitmq:mqtt'
        run: |
          docker build \
              --file images/rabbitmq/mqtt/Dockerfile \
              --build-arg IMAGE_PREFIX=${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }} \
              --tag ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/rabbitmq:mqtt \
              images/rabbitmq/mqtt/

      - name: Login to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push '${{ github.repository_owner }}/rabbitmq:latest'
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/rabbitmq:latest

      - name: Push '${{ github.repository_owner }}/rabbitmq:mqtt'
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/rabbitmq:mqtt
